name: Unity PlayMode Tests

on:
  push:
    branches: [main, Automatization-Tests]
  pull_request:

jobs:
  playmode-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PlayMode tests
        shell: powershell
        run: |
          $unityPath = "C:\Program Files\Unity\Hub\Editor\2022.3.62f1\Editor\Unity.exe"
          $projectPath = "${{ github.workspace }}"
          $logFile = "$projectPath\playmode-log.txt"
          $resultsFile = "$projectPath\playmode-results.xml"

          & "$unityPath" -runTests `
            -projectPath "$projectPath" `
            -testPlatform PlayMode `
            -logfile "$logFile" `
            -testResults "$resultsFile" `
            -batchmode `
            -nographics `
            -quit

      - name: Upload PlayMode test results
        uses: actions/upload-artifact@v3
        with:
          name: playmode-test-results
          path: playmode-results.xml
